#!/bin/sh
dir=$(dirname "$0")

echo " --- [start cluster] ---"
kind create cluster --wait 5m --name prom-test

if [ "$(kubectl config current-context)" != "kind-prom-test" ]
then
  echo "kubectl context is not set to kind-prom-test"
  exit 1
fi

# install prometheus chart
kubectl create ns prometheus
helm install prometheus prometheus-community/prometheus \
  --namespace prometheus \
  --wait

echo "cluster is running, to delete cluster run"
echo "kind delete cluster --name prom-test"
